version: "3.9"

services:
  react-frontend:
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - spring-backend

  spring-backend:
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crowdfunding

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: crowdfunding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tombo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
